### ISSUE TITLE
Некорректный подсчет страниц при использовании \include

### ISSUE THREAD

**Issue by Ryazantsev-val** [alex-chaplygin/vkr-latex#11]
Судя по описанию, которое удалось найти, команда \include вызывает \clearpage до и после содержимого файла, что в случае с примером (и с моей версией диплома) сломало подсчет страниц.
Ваш pdf-файл выглядит так:
![image](https://github.com/alex-chaplygin/vkr-latex/assets/71129635/32daa0b6-c574-4df8-ad84-367213bbcb87)
Из-за этого переноса количество страниц в реферате совпадает с количеством страниц в документе.

Однако при компиляции в TexStudio на Windows получается так (проверено на двух компьютерах):
![image](https://github.com/alex-chaplygin/vkr-latex/assets/71129635/1539db24-c279-4fbb-b88a-61ba6611004b)

А вот счетчик страниц по-прежнему видит там новую страницу и выдает неправильный результат: 
![image](https://github.com/alex-chaplygin/vkr-latex/assets/71129635/5da80648-a315-4c5e-b049-77432b12237b)

Если заменить \include на \input в main.tex и каждый файл начинать командой \newsection, то такой проблемы нет (до этих изменений страницы также считались правильно):
![image](https://github.com/alex-chaplygin/vkr-latex/assets/71129635/9d07ec22-859d-4f8a-b136-f8254e7883eb)

Тем более, команда \newsection все равно остается в начале большинства разделов для корректировки нумерации таблиц и рисунков, так мы только всех запутаем, когда ее использовать, а когда нет.

**Comment by Ryazantsev-val** [comment]
Если будет возможность, попробуйте скомпилировать версию из моего репозитория и посмотреть, как поведет себя счетчик количества страниц.

https://github.com/Ryazantsev-val/vkr-latex

**Comment by alex-chaplygin** [comment]
По смыслу, все таки правильно \include, тем более что очищать счетчики в реферате, введении не нужно. В заключении не бывает рисунков. Остаются только приложения. По хорошему очищение счетчиков должно быть не отдельной командой, а внутри \section. Вопрос - почему у меня абзац переносится, а у вас нет?

**Comment by alex-chaplygin** [comment]
Я попробовал твой вариант. В твоем варианте считает 43, у меня считает 44

**Comment by alex-chaplygin** [comment]
Абзац переносится в обоих случаях.

**Comment by Ryazantsev-val** [comment]
> Вопрос - почему у меня абзац переносится, а у вас нет?

Из-за незначительных отличий в высоте ячеек таблицы (3.3). Слева мой вариант, справа ваш.
![image](https://github.com/alex-chaplygin/vkr-latex/assets/71129635/9081f10b-9361-4805-8217-67b676548ee6)

**Comment by Ryazantsev-val** [comment]
Если еще точнее, то дело в разном отступе снизу у некоторых строк таблицы (но не у всех, например, у первой и последней строки размеры полностью совпадают)

![image](https://github.com/alex-chaplygin/vkr-latex/assets/71129635/eb7cb0f8-b8da-4406-9e93-fe09de104b3d)

Предположу, что дело в этом коммите: https://github.com/alex-chaplygin/vkr-latex/commit/e5c97ab1474d89f6925a18e2900b1631a580b706

У меня данный пакет не требовался, компиляция проходила и без него. Сейчас он добавлен, но при компиляции в TexStudio на Windows не используется: его удаление из setup.tex ничего в документе не меняет.
Можете, пожалуйста, уточнить, какая ошибка у вас возникает, если убрать пакет setspace?

**Comment by alex-chaplygin** [comment]
Если убрать setspace, то не найдено \setstretch
! Undefined control sequence.
\captionfont ->\setstretch 
                           {\onehalflinespread }
l.96 \end{xltabular}

**Comment by Ryazantsev-val** [comment]
Судя по описанию, проблема связана с пакетом caption. Он достаточно активно обновляется, актуальная версия 3.6 выпущена в марте 2023 года, а в ноябре 2021 был подходящий коммит: https://gitlab.com/axelsommerfeldt/caption/-/commit/2151c47a692a8c4b71c87836c51a21f47c195cf2
![image](https://github.com/alex-chaplygin/vkr-latex/assets/71129635/e775098c-72c3-4fc6-a233-0c138a94dbe3)

Попробуйте установить актуальную версию пакета Caption и проверить, пропадет ли перенос на следующую страницу.

**Comment by alex-chaplygin** [comment]
Все равно абзац переносится. Можно вернутся к \input, хотя разница в одну страницу может быть не существенна (например место для диска возможно не должно попадать в число страниц). На этом варианте пока стоит остановится. Я решил сделать новый класс документа для ВКР, а то у нас получилась слишком большая преамбула, куча пакетов. Собственно уже сделал много. Например, чтобы \section начинал новую страницу, \abstract для рефератов, \appendix для приложений (автоматически ставится А, Б и т.д.). Сторонние пакеты только babel,graphicsx и скорей всего xltabular и biblatex. Библиографию имеет смысл сделать автоматическую по базе. Стиль gost есть встроенный.

**Comment by Ryazantsev-val** [comment]
В любом случае, отличие документов должно объясняться версиями LaTeX или установленных пакетов.
Например, в сентябре 21 года обновился и пакет longtable, он входит в комплект поставки системы, поэтому не знаю, можно ли обновить его отдельно.

По поводу стиля библиографии, я нашел якобы сделанный по ГОСТ 2018 файл, но работал он так себе. Например, там отсутствовал ISBN, хотя он явно требуется по стандарту.

Я использовал Zotero для формирования списка источников, разбираться с библиографией на стороне LaTeX не стал. Например, с установкой расширения Zotero Connector можно в одно нажатие импортировать из Google Книг (а там есть почти все изданные в бумажном виде книги) метаданные документа, а потом еще двумя кликами скопировать в буфер обмена источник в подходящем формате. 

Вероятно, существует исправленная версия стиля, но может, мои правки будут полезны: https://github.com/Ryazantsev-val/vkr-latex/commit/da02eda2f04e9d014bafac433a4637b2ce6fd803

**Comment by alex-chaplygin** [comment]
Спасибо, я посмотрю потом.
Насчет посчета страниц я сделал в классе надежный способ посчета:
% подсчет страниц
\newcounter{lastpage}
\setcounter{lastpage}{0}
% пишем в aux файл команду установки счетчика на номер последней страницы
% aux файл автоматически читается в начале документа
\def\@enddocumenthook{\immediate\write\@auxout%
  {\string\setcounter{lastpage}{\the\c@page}}}
то есть сколько получилось страниц, столько и установится в счетчике
